name: crispr-evo
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - git=2.52.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.45
  - libcurl=8.17.0
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pcre2=10.47
  - perl=5.32.1
  - pip=25.3
  - python=3.12.12
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - attrs==25.4.0
      - biopython==1.86
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - datasets==3.0.2
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - evaluate==0.4.6
      - filelock==3.20.0
      - flash-attn==2.7.4.post1
      - frozenlist==1.8.0
      - fsspec==2024.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - networkx==3.6
      - numpy==2.3.5
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - packaging==25.0
      - pandas==2.3.3
      - peft==0.14.0
      - platformdirs==4.5.1
      - propcache==0.4.1
      - protobuf==5.29.5
      - psutil==7.1.3
      - pyarrow==22.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.5.2
      - scipy==1.16.3
      - sentry-sdk==2.47.0
      - setproctitle==1.3.7
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.20.3
      - torch==2.7.0
      - tqdm==4.67.1
      - transformers==4.45.2
      - triton==3.3.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.6.0
      - wandb==0.18.7
      - xxhash==3.6.0
      - yarl==1.22.0
